### ISSUE TITLE
always failed to save cookies

### ISSUE THREAD

**Issue by prakasa1904** [bsidelinger912/isomorphic-cookie#4]
I duno whats I mistakes with this one, already follow every step in examples code but still fail to save my cookies. Code examples bellow : 

Cookies.save('a', 'wwwwwwwwwwwwwwwwwww')

there, I miss something ?

my packages is not block this libs right, expept lodash  ?
dependencies:
"lodash": "4.17.4",

**Comment by bsidelinger912** [comment]
Hi Prakasa, 
I'll need some more info to help you.  Are you doing this on a node server or in the browser?  Are you sure your importing or requiring the package correctly (you don't show me your import/require code)?  In a node server you need pass the response object so we can update the set-cookie header.  In the browser, you should see the cookie show up in dev tools (application tab in chrome).  How are you confirming that the cookie is saved or not?

**Comment by bsidelinger912** [comment]
Hi Prakasa, 
One thing I thought of is that you need to pass the option { secure: false } if your using on an http connection, such as localhost.  I've updated the readme to better explain this.

**Comment by bsidelinger912** [comment]
Closing as I believe the updated documentation covers this issue.
